# ------------------------------------------------------------------------- #
#                               Build image                                 #
# ------------------------------------------------------------------------- #
FROM node:lts-alpine AS build
RUN mkdir /app
WORKDIR /app
COPY ./maintenance/src .

# ------------------------------------------------------------------------- #
#                               Prod image                                  #
# ------------------------------------------------------------------------- #
FROM nginx:stable-alpine AS server
COPY --from=build /app /var/www/html
COPY ./maintenance/nginx.conf /etc/nginx/nginx.conf